include:
    - local: 'variables.yml'
    - local: 'merge-request.yml'
    - local: 'production.yml'
    - local: 'staging.yml'
    - local: 'notification.yml'

stages:
  - test source code
  - build
  - security scan image
  - push image
  - deploy
  - performance testing
  - send report
