apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: todolist-backend-autoscaler
  namespace: todolist
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todolist-backend-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
