apiVersion: v1
kind: Service
metadata:
  name: todolist-frontend-service
  namespace: todolist
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: todolist-frontend
