apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: todolist-frontend-autoscaler
  namespace: todolist
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todolist-frontend-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
